//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.2
//     from Assets/MyAssets/InputSystem/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace URPMk2
{
    public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PlayerInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Controllable"",
            ""id"": ""9c605f07-25ba-4c78-b59d-e42bbdd95e6c"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""fbc27592-1700-448b-8037-f147bc7d0214"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""623d70ba-f635-4372-8258-fbae3a7e5929"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""207da09e-bb0e-4bb4-ba98-fe5cf5e8decc"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseX"",
                    ""type"": ""PassThrough"",
                    ""id"": ""810eb233-b1d6-49e2-bdf6-feec6e5219e5"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseY"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b288906d-2cff-41e2-9763-70d72bef5b4e"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a15c0794-6f52-42fa-8168-98676fe64e27"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WSAD"",
                    ""id"": ""8fbca4b4-3645-49da-91c7-29b4217e4af1"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""eff0a16e-a30e-4962-83db-e868ad5c5def"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""87b39951-afe4-4461-b3fc-9465a98001b3"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""47cb8564-7f25-463e-be47-287865b11cef"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0cbbe058-ba5f-45fd-9ea9-4106b8799ecb"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8f0dbdcc-375d-4f26-80f6-9cc92449d110"",
                    ""path"": ""<Mouse>/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38c4a958-fdbb-4944-90d1-6158f481c0ed"",
                    ""path"": ""<Mouse>/delta/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02f7e0dd-afb8-47de-a5be-ab0d3c4669c8"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Humanoid"",
            ""id"": ""5608d37f-2245-4511-8c93-89daf35c07e2"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""1d131a1a-488a-4151-8110-84b9a28751db"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RunStart"",
                    ""type"": ""Button"",
                    ""id"": ""dc2cdf78-502f-46b3-975c-355cb0664763"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RunFinish"",
                    ""type"": ""Button"",
                    ""id"": ""a7630a66-b323-4c1d-8fcd-5862135f25d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""7e64ed83-52ef-4d0d-b87e-c7c4af527883"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseX"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f6a54e77-6abb-436b-9f3f-435ccc87f048"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseY"",
                    ""type"": ""PassThrough"",
                    ""id"": ""861deee6-e9fe-4edc-9353-52c9e62510e9"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ItemInteract"",
                    ""type"": ""Button"",
                    ""id"": ""2982b9f9-f533-420c-a723-1618eb18da34"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ItemThrow"",
                    ""type"": ""Button"",
                    ""id"": ""346ba0e3-4296-4023-92b3-e5e2cb491a70"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleInventory"",
                    ""type"": ""Button"",
                    ""id"": ""35431b0d-5fdf-4b6d-a65c-8b9369598cba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Button"",
                    ""id"": ""89acea72-66c4-46b9-8431-ed4ecc3f3cb8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""aef70b32-5250-4e8d-9ff9-b3d0bd925f5a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""fd7f693c-3bef-46fe-a815-c10119b2dcab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeFireMode"",
                    ""type"": ""Button"",
                    ""id"": ""04e52dc5-8fd7-4597-b1ed-25a4abcbe5f2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleDamageSettings"",
                    ""type"": ""Button"",
                    ""id"": ""0bc8ccce-043a-4b03-88c2-6f3912f73d25"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WSAD"",
                    ""id"": ""e43f5b59-88b0-4d6b-ab0d-c50f09ab5c5f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""85681ee5-de16-474e-8f77-e4a9db240cc5"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""da63512f-6ff4-4ef5-8a04-e77fba0a316c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ed30353b-ce44-4aca-810b-d4ebacd1c17b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b4b90aa9-64ac-417d-b6da-9a0bf07b6a82"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""48c18255-8ac4-42b1-a38d-8c7378d827fd"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0c4493dc-e33e-46ed-8252-056512667bbd"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a996dd39-c49c-4162-bf11-e0f442619f27"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2c7ff52f-c2e5-4ca0-b8dc-5d1a62dc769f"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9d47fc54-c1de-4a7b-855e-39d60e3ef0b7"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""182980dc-caba-4ccb-b3d5-7ff1e90f525a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb877596-1249-437a-8c9d-440368dbf204"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RunStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29aec921-6ac5-403a-91aa-eb004f0f727a"",
                    ""path"": ""<Mouse>/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a011140a-46b9-4040-a9c1-e2551f0f224b"",
                    ""path"": ""<Mouse>/delta/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c1cc09c-9b33-4f91-9beb-5ff85e882853"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RunFinish"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0aec56ac-b1d6-4037-9620-b573aa7090d7"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ItemInteract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b82e8348-7028-4af8-86eb-f98e9b74f7d0"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ItemThrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0306d550-ac3a-4430-acdf-d218889e8a20"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""164d35c3-1225-4aeb-86eb-58e98d0ba520"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""434a3194-cb72-486f-8c54-6cf879a4014b"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fcbb61ea-7476-4127-abf1-62f9763e96dc"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a355069-900f-44a0-a9fe-3eb68064f6a4"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeFireMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75eeeb01-b481-4d9c-b3ff-fb54d8a721f2"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleDamageSettings"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""c9a52d2c-0047-406f-b014-48093ee5d906"",
            ""actions"": [
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""59456348-a897-408e-a43b-917d35cde079"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""1a8e1a32-833d-4171-af5b-46312e4704c5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""6f20216c-7188-43df-811b-4d1468b8ecae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0133e13a-0e06-415e-8b08-2d2e55d60d70"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""PassThrough"",
                    ""id"": ""053ea104-508f-478d-8116-da021aad22ec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ScrollWheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""dd0fcf2b-7026-48ab-b3da-ae4f7baa1fe4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MiddleClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""bae3deae-785e-45f0-b098-576ec6623e79"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""49d9245e-4201-45b9-8360-5c354a98e36a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackedDevicePosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a812b92b-c705-4ac4-a286-c151ae31e51d"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackedDeviceOrientation"",
                    ""type"": ""PassThrough"",
                    ""id"": ""99d6e9d3-0895-4b2e-84c2-8d1be3664ce9"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleInventory"",
                    ""type"": ""Button"",
                    ""id"": ""2466e617-2215-40ec-99ad-f7e7cfc04d02"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleDamageScreen"",
                    ""type"": ""Button"",
                    ""id"": ""e970f663-6ab1-4c7c-b4e5-161db09d8513"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""c8d91ca9-8d76-4061-a2d0-9a0ffe6ab231"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3044a34e-e9be-4cd2-b564-5af7e968df95"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f5cd0f90-8f8c-4040-a179-101ec1f93d4a"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8b2f81d9-7091-41d8-91ae-8ffca4147578"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0632b2f5-f93a-41fa-9b72-680b09513d56"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6b2f1088-7ece-41a8-858f-62ec627ba9aa"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""37da322e-8517-43fb-b7be-12b0ac5bfef3"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3aba70c1-26cd-41bc-aeab-ba78e7b68b9e"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b13fca67-71fb-486c-a16a-42c5272335a5"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a58ae7e2-4e38-44e7-92c3-d22e4f024603"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""4f40007a-6b6a-486e-acb2-14a97ce7f4a1"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""430a8b0a-73f4-4a55-9754-a7d430d3d3de"",
                    ""path"": ""<Joystick>/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2471b045-4d89-4489-a809-e7edcd8e0877"",
                    ""path"": ""<Joystick>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""cb300381-a903-4f69-b8a2-d85f3f4b731c"",
                    ""path"": ""<Joystick>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c80a7094-d9b2-45c9-bf70-124af5af9b25"",
                    ""path"": ""<Joystick>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""d25c76d4-c637-4195-9768-90e320c75c36"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""549daaec-be11-49a7-b4bb-0aac89095bcb"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ef54ac2a-c3d1-44bf-b8dd-a59ad929f6e0"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3df5fa37-a88e-4495-9bc9-93fda883f734"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0dde0b2a-f7cb-4ba1-be5f-ba2a46ae578d"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8041c224-16a3-426b-8552-bdb8e134707b"",
                    ""path"": ""*/{Submit}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d249d5f-ebbe-4bee-875f-9c9d8a5f82b6"",
                    ""path"": ""*/{Cancel}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa0a6983-55d9-4855-be80-610699309f25"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""348f4f0d-b36b-4355-bd11-016af46a692a"",
                    ""path"": ""<Pen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90df5021-7e2d-466d-b3e5-e3f325810646"",
                    ""path"": ""<Touchscreen>/touch*/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8f6ebee-49f1-4555-aac8-d7fbc90dbf5d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08b176af-0608-4a03-9e32-48cb07231be2"",
                    ""path"": ""<Pen>/tip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2830b876-8ae6-44d9-8b30-59d5ca343519"",
                    ""path"": ""<Touchscreen>/touch*/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ceaa880-73b5-4c34-9a35-73051d32f0c9"",
                    ""path"": ""<XRController>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d09a2887-7410-4063-8906-802d18d5bdfc"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""ScrollWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d42756a-fef0-4137-a5e2-abea7895add4"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""MiddleClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76cd627f-3c31-4cf1-80b5-8e8844e9f134"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b72a5ed8-3bbb-4cad-a6f0-139d6253de6e"",
                    ""path"": ""<XRController>/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""TrackedDevicePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea812ea3-28e7-4cd9-bec2-d4eac3dc2384"",
                    ""path"": ""<XRController>/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""TrackedDeviceOrientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""445a6bab-d614-4e03-8da7-c2d2d2f4b0b2"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41cadc09-b5c4-4e6e-8a71-3d606bccdad1"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleDamageScreen"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Controllable
            m_Controllable = asset.FindActionMap("Controllable", throwIfNotFound: true);
            m_Controllable_Jump = m_Controllable.FindAction("Jump", throwIfNotFound: true);
            m_Controllable_Run = m_Controllable.FindAction("Run", throwIfNotFound: true);
            m_Controllable_Move = m_Controllable.FindAction("Move", throwIfNotFound: true);
            m_Controllable_MouseX = m_Controllable.FindAction("MouseX", throwIfNotFound: true);
            m_Controllable_MouseY = m_Controllable.FindAction("MouseY", throwIfNotFound: true);
            // Humanoid
            m_Humanoid = asset.FindActionMap("Humanoid", throwIfNotFound: true);
            m_Humanoid_Move = m_Humanoid.FindAction("Move", throwIfNotFound: true);
            m_Humanoid_RunStart = m_Humanoid.FindAction("RunStart", throwIfNotFound: true);
            m_Humanoid_RunFinish = m_Humanoid.FindAction("RunFinish", throwIfNotFound: true);
            m_Humanoid_Jump = m_Humanoid.FindAction("Jump", throwIfNotFound: true);
            m_Humanoid_MouseX = m_Humanoid.FindAction("MouseX", throwIfNotFound: true);
            m_Humanoid_MouseY = m_Humanoid.FindAction("MouseY", throwIfNotFound: true);
            m_Humanoid_ItemInteract = m_Humanoid.FindAction("ItemInteract", throwIfNotFound: true);
            m_Humanoid_ItemThrow = m_Humanoid.FindAction("ItemThrow", throwIfNotFound: true);
            m_Humanoid_ToggleInventory = m_Humanoid.FindAction("ToggleInventory", throwIfNotFound: true);
            m_Humanoid_Aim = m_Humanoid.FindAction("Aim", throwIfNotFound: true);
            m_Humanoid_Shoot = m_Humanoid.FindAction("Shoot", throwIfNotFound: true);
            m_Humanoid_Reload = m_Humanoid.FindAction("Reload", throwIfNotFound: true);
            m_Humanoid_ChangeFireMode = m_Humanoid.FindAction("ChangeFireMode", throwIfNotFound: true);
            m_Humanoid_ToggleDamageSettings = m_Humanoid.FindAction("ToggleDamageSettings", throwIfNotFound: true);
            // UI
            m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
            m_UI_Navigate = m_UI.FindAction("Navigate", throwIfNotFound: true);
            m_UI_Submit = m_UI.FindAction("Submit", throwIfNotFound: true);
            m_UI_Cancel = m_UI.FindAction("Cancel", throwIfNotFound: true);
            m_UI_Point = m_UI.FindAction("Point", throwIfNotFound: true);
            m_UI_Click = m_UI.FindAction("Click", throwIfNotFound: true);
            m_UI_ScrollWheel = m_UI.FindAction("ScrollWheel", throwIfNotFound: true);
            m_UI_MiddleClick = m_UI.FindAction("MiddleClick", throwIfNotFound: true);
            m_UI_RightClick = m_UI.FindAction("RightClick", throwIfNotFound: true);
            m_UI_TrackedDevicePosition = m_UI.FindAction("TrackedDevicePosition", throwIfNotFound: true);
            m_UI_TrackedDeviceOrientation = m_UI.FindAction("TrackedDeviceOrientation", throwIfNotFound: true);
            m_UI_ToggleInventory = m_UI.FindAction("ToggleInventory", throwIfNotFound: true);
            m_UI_ToggleDamageScreen = m_UI.FindAction("ToggleDamageScreen", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Controllable
        private readonly InputActionMap m_Controllable;
        private IControllableActions m_ControllableActionsCallbackInterface;
        private readonly InputAction m_Controllable_Jump;
        private readonly InputAction m_Controllable_Run;
        private readonly InputAction m_Controllable_Move;
        private readonly InputAction m_Controllable_MouseX;
        private readonly InputAction m_Controllable_MouseY;
        public struct ControllableActions
        {
            private @PlayerInputActions m_Wrapper;
            public ControllableActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Jump => m_Wrapper.m_Controllable_Jump;
            public InputAction @Run => m_Wrapper.m_Controllable_Run;
            public InputAction @Move => m_Wrapper.m_Controllable_Move;
            public InputAction @MouseX => m_Wrapper.m_Controllable_MouseX;
            public InputAction @MouseY => m_Wrapper.m_Controllable_MouseY;
            public InputActionMap Get() { return m_Wrapper.m_Controllable; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(ControllableActions set) { return set.Get(); }
            public void SetCallbacks(IControllableActions instance)
            {
                if (m_Wrapper.m_ControllableActionsCallbackInterface != null)
                {
                    @Jump.started -= m_Wrapper.m_ControllableActionsCallbackInterface.OnJump;
                    @Jump.performed -= m_Wrapper.m_ControllableActionsCallbackInterface.OnJump;
                    @Jump.canceled -= m_Wrapper.m_ControllableActionsCallbackInterface.OnJump;
                    @Run.started -= m_Wrapper.m_ControllableActionsCallbackInterface.OnRun;
                    @Run.performed -= m_Wrapper.m_ControllableActionsCallbackInterface.OnRun;
                    @Run.canceled -= m_Wrapper.m_ControllableActionsCallbackInterface.OnRun;
                    @Move.started -= m_Wrapper.m_ControllableActionsCallbackInterface.OnMove;
                    @Move.performed -= m_Wrapper.m_ControllableActionsCallbackInterface.OnMove;
                    @Move.canceled -= m_Wrapper.m_ControllableActionsCallbackInterface.OnMove;
                    @MouseX.started -= m_Wrapper.m_ControllableActionsCallbackInterface.OnMouseX;
                    @MouseX.performed -= m_Wrapper.m_ControllableActionsCallbackInterface.OnMouseX;
                    @MouseX.canceled -= m_Wrapper.m_ControllableActionsCallbackInterface.OnMouseX;
                    @MouseY.started -= m_Wrapper.m_ControllableActionsCallbackInterface.OnMouseY;
                    @MouseY.performed -= m_Wrapper.m_ControllableActionsCallbackInterface.OnMouseY;
                    @MouseY.canceled -= m_Wrapper.m_ControllableActionsCallbackInterface.OnMouseY;
                }
                m_Wrapper.m_ControllableActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Jump.started += instance.OnJump;
                    @Jump.performed += instance.OnJump;
                    @Jump.canceled += instance.OnJump;
                    @Run.started += instance.OnRun;
                    @Run.performed += instance.OnRun;
                    @Run.canceled += instance.OnRun;
                    @Move.started += instance.OnMove;
                    @Move.performed += instance.OnMove;
                    @Move.canceled += instance.OnMove;
                    @MouseX.started += instance.OnMouseX;
                    @MouseX.performed += instance.OnMouseX;
                    @MouseX.canceled += instance.OnMouseX;
                    @MouseY.started += instance.OnMouseY;
                    @MouseY.performed += instance.OnMouseY;
                    @MouseY.canceled += instance.OnMouseY;
                }
            }
        }
        public ControllableActions @Controllable => new ControllableActions(this);

        // Humanoid
        private readonly InputActionMap m_Humanoid;
        private IHumanoidActions m_HumanoidActionsCallbackInterface;
        private readonly InputAction m_Humanoid_Move;
        private readonly InputAction m_Humanoid_RunStart;
        private readonly InputAction m_Humanoid_RunFinish;
        private readonly InputAction m_Humanoid_Jump;
        private readonly InputAction m_Humanoid_MouseX;
        private readonly InputAction m_Humanoid_MouseY;
        private readonly InputAction m_Humanoid_ItemInteract;
        private readonly InputAction m_Humanoid_ItemThrow;
        private readonly InputAction m_Humanoid_ToggleInventory;
        private readonly InputAction m_Humanoid_Aim;
        private readonly InputAction m_Humanoid_Shoot;
        private readonly InputAction m_Humanoid_Reload;
        private readonly InputAction m_Humanoid_ChangeFireMode;
        private readonly InputAction m_Humanoid_ToggleDamageSettings;
        public struct HumanoidActions
        {
            private @PlayerInputActions m_Wrapper;
            public HumanoidActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_Humanoid_Move;
            public InputAction @RunStart => m_Wrapper.m_Humanoid_RunStart;
            public InputAction @RunFinish => m_Wrapper.m_Humanoid_RunFinish;
            public InputAction @Jump => m_Wrapper.m_Humanoid_Jump;
            public InputAction @MouseX => m_Wrapper.m_Humanoid_MouseX;
            public InputAction @MouseY => m_Wrapper.m_Humanoid_MouseY;
            public InputAction @ItemInteract => m_Wrapper.m_Humanoid_ItemInteract;
            public InputAction @ItemThrow => m_Wrapper.m_Humanoid_ItemThrow;
            public InputAction @ToggleInventory => m_Wrapper.m_Humanoid_ToggleInventory;
            public InputAction @Aim => m_Wrapper.m_Humanoid_Aim;
            public InputAction @Shoot => m_Wrapper.m_Humanoid_Shoot;
            public InputAction @Reload => m_Wrapper.m_Humanoid_Reload;
            public InputAction @ChangeFireMode => m_Wrapper.m_Humanoid_ChangeFireMode;
            public InputAction @ToggleDamageSettings => m_Wrapper.m_Humanoid_ToggleDamageSettings;
            public InputActionMap Get() { return m_Wrapper.m_Humanoid; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(HumanoidActions set) { return set.Get(); }
            public void SetCallbacks(IHumanoidActions instance)
            {
                if (m_Wrapper.m_HumanoidActionsCallbackInterface != null)
                {
                    @Move.started -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnMove;
                    @Move.performed -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnMove;
                    @Move.canceled -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnMove;
                    @RunStart.started -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnRunStart;
                    @RunStart.performed -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnRunStart;
                    @RunStart.canceled -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnRunStart;
                    @RunFinish.started -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnRunFinish;
                    @RunFinish.performed -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnRunFinish;
                    @RunFinish.canceled -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnRunFinish;
                    @Jump.started -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnJump;
                    @Jump.performed -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnJump;
                    @Jump.canceled -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnJump;
                    @MouseX.started -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnMouseX;
                    @MouseX.performed -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnMouseX;
                    @MouseX.canceled -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnMouseX;
                    @MouseY.started -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnMouseY;
                    @MouseY.performed -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnMouseY;
                    @MouseY.canceled -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnMouseY;
                    @ItemInteract.started -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnItemInteract;
                    @ItemInteract.performed -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnItemInteract;
                    @ItemInteract.canceled -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnItemInteract;
                    @ItemThrow.started -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnItemThrow;
                    @ItemThrow.performed -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnItemThrow;
                    @ItemThrow.canceled -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnItemThrow;
                    @ToggleInventory.started -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnToggleInventory;
                    @ToggleInventory.performed -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnToggleInventory;
                    @ToggleInventory.canceled -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnToggleInventory;
                    @Aim.started -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnAim;
                    @Aim.performed -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnAim;
                    @Aim.canceled -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnAim;
                    @Shoot.started -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnShoot;
                    @Shoot.performed -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnShoot;
                    @Shoot.canceled -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnShoot;
                    @Reload.started -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnReload;
                    @Reload.performed -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnReload;
                    @Reload.canceled -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnReload;
                    @ChangeFireMode.started -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnChangeFireMode;
                    @ChangeFireMode.performed -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnChangeFireMode;
                    @ChangeFireMode.canceled -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnChangeFireMode;
                    @ToggleDamageSettings.started -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnToggleDamageSettings;
                    @ToggleDamageSettings.performed -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnToggleDamageSettings;
                    @ToggleDamageSettings.canceled -= m_Wrapper.m_HumanoidActionsCallbackInterface.OnToggleDamageSettings;
                }
                m_Wrapper.m_HumanoidActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Move.started += instance.OnMove;
                    @Move.performed += instance.OnMove;
                    @Move.canceled += instance.OnMove;
                    @RunStart.started += instance.OnRunStart;
                    @RunStart.performed += instance.OnRunStart;
                    @RunStart.canceled += instance.OnRunStart;
                    @RunFinish.started += instance.OnRunFinish;
                    @RunFinish.performed += instance.OnRunFinish;
                    @RunFinish.canceled += instance.OnRunFinish;
                    @Jump.started += instance.OnJump;
                    @Jump.performed += instance.OnJump;
                    @Jump.canceled += instance.OnJump;
                    @MouseX.started += instance.OnMouseX;
                    @MouseX.performed += instance.OnMouseX;
                    @MouseX.canceled += instance.OnMouseX;
                    @MouseY.started += instance.OnMouseY;
                    @MouseY.performed += instance.OnMouseY;
                    @MouseY.canceled += instance.OnMouseY;
                    @ItemInteract.started += instance.OnItemInteract;
                    @ItemInteract.performed += instance.OnItemInteract;
                    @ItemInteract.canceled += instance.OnItemInteract;
                    @ItemThrow.started += instance.OnItemThrow;
                    @ItemThrow.performed += instance.OnItemThrow;
                    @ItemThrow.canceled += instance.OnItemThrow;
                    @ToggleInventory.started += instance.OnToggleInventory;
                    @ToggleInventory.performed += instance.OnToggleInventory;
                    @ToggleInventory.canceled += instance.OnToggleInventory;
                    @Aim.started += instance.OnAim;
                    @Aim.performed += instance.OnAim;
                    @Aim.canceled += instance.OnAim;
                    @Shoot.started += instance.OnShoot;
                    @Shoot.performed += instance.OnShoot;
                    @Shoot.canceled += instance.OnShoot;
                    @Reload.started += instance.OnReload;
                    @Reload.performed += instance.OnReload;
                    @Reload.canceled += instance.OnReload;
                    @ChangeFireMode.started += instance.OnChangeFireMode;
                    @ChangeFireMode.performed += instance.OnChangeFireMode;
                    @ChangeFireMode.canceled += instance.OnChangeFireMode;
                    @ToggleDamageSettings.started += instance.OnToggleDamageSettings;
                    @ToggleDamageSettings.performed += instance.OnToggleDamageSettings;
                    @ToggleDamageSettings.canceled += instance.OnToggleDamageSettings;
                }
            }
        }
        public HumanoidActions @Humanoid => new HumanoidActions(this);

        // UI
        private readonly InputActionMap m_UI;
        private IUIActions m_UIActionsCallbackInterface;
        private readonly InputAction m_UI_Navigate;
        private readonly InputAction m_UI_Submit;
        private readonly InputAction m_UI_Cancel;
        private readonly InputAction m_UI_Point;
        private readonly InputAction m_UI_Click;
        private readonly InputAction m_UI_ScrollWheel;
        private readonly InputAction m_UI_MiddleClick;
        private readonly InputAction m_UI_RightClick;
        private readonly InputAction m_UI_TrackedDevicePosition;
        private readonly InputAction m_UI_TrackedDeviceOrientation;
        private readonly InputAction m_UI_ToggleInventory;
        private readonly InputAction m_UI_ToggleDamageScreen;
        public struct UIActions
        {
            private @PlayerInputActions m_Wrapper;
            public UIActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Navigate => m_Wrapper.m_UI_Navigate;
            public InputAction @Submit => m_Wrapper.m_UI_Submit;
            public InputAction @Cancel => m_Wrapper.m_UI_Cancel;
            public InputAction @Point => m_Wrapper.m_UI_Point;
            public InputAction @Click => m_Wrapper.m_UI_Click;
            public InputAction @ScrollWheel => m_Wrapper.m_UI_ScrollWheel;
            public InputAction @MiddleClick => m_Wrapper.m_UI_MiddleClick;
            public InputAction @RightClick => m_Wrapper.m_UI_RightClick;
            public InputAction @TrackedDevicePosition => m_Wrapper.m_UI_TrackedDevicePosition;
            public InputAction @TrackedDeviceOrientation => m_Wrapper.m_UI_TrackedDeviceOrientation;
            public InputAction @ToggleInventory => m_Wrapper.m_UI_ToggleInventory;
            public InputAction @ToggleDamageScreen => m_Wrapper.m_UI_ToggleDamageScreen;
            public InputActionMap Get() { return m_Wrapper.m_UI; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
            public void SetCallbacks(IUIActions instance)
            {
                if (m_Wrapper.m_UIActionsCallbackInterface != null)
                {
                    @Navigate.started -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                    @Navigate.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                    @Navigate.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                    @Submit.started -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                    @Submit.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                    @Submit.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                    @Cancel.started -= m_Wrapper.m_UIActionsCallbackInterface.OnCancel;
                    @Cancel.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnCancel;
                    @Cancel.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnCancel;
                    @Point.started -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                    @Point.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                    @Point.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                    @Click.started -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                    @Click.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                    @Click.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                    @ScrollWheel.started -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                    @ScrollWheel.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                    @ScrollWheel.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                    @MiddleClick.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                    @MiddleClick.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                    @MiddleClick.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                    @RightClick.started -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                    @RightClick.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                    @RightClick.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                    @TrackedDevicePosition.started -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDevicePosition;
                    @TrackedDevicePosition.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDevicePosition;
                    @TrackedDevicePosition.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDevicePosition;
                    @TrackedDeviceOrientation.started -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDeviceOrientation;
                    @TrackedDeviceOrientation.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDeviceOrientation;
                    @TrackedDeviceOrientation.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDeviceOrientation;
                    @ToggleInventory.started -= m_Wrapper.m_UIActionsCallbackInterface.OnToggleInventory;
                    @ToggleInventory.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnToggleInventory;
                    @ToggleInventory.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnToggleInventory;
                    @ToggleDamageScreen.started -= m_Wrapper.m_UIActionsCallbackInterface.OnToggleDamageScreen;
                    @ToggleDamageScreen.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnToggleDamageScreen;
                    @ToggleDamageScreen.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnToggleDamageScreen;
                }
                m_Wrapper.m_UIActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Navigate.started += instance.OnNavigate;
                    @Navigate.performed += instance.OnNavigate;
                    @Navigate.canceled += instance.OnNavigate;
                    @Submit.started += instance.OnSubmit;
                    @Submit.performed += instance.OnSubmit;
                    @Submit.canceled += instance.OnSubmit;
                    @Cancel.started += instance.OnCancel;
                    @Cancel.performed += instance.OnCancel;
                    @Cancel.canceled += instance.OnCancel;
                    @Point.started += instance.OnPoint;
                    @Point.performed += instance.OnPoint;
                    @Point.canceled += instance.OnPoint;
                    @Click.started += instance.OnClick;
                    @Click.performed += instance.OnClick;
                    @Click.canceled += instance.OnClick;
                    @ScrollWheel.started += instance.OnScrollWheel;
                    @ScrollWheel.performed += instance.OnScrollWheel;
                    @ScrollWheel.canceled += instance.OnScrollWheel;
                    @MiddleClick.started += instance.OnMiddleClick;
                    @MiddleClick.performed += instance.OnMiddleClick;
                    @MiddleClick.canceled += instance.OnMiddleClick;
                    @RightClick.started += instance.OnRightClick;
                    @RightClick.performed += instance.OnRightClick;
                    @RightClick.canceled += instance.OnRightClick;
                    @TrackedDevicePosition.started += instance.OnTrackedDevicePosition;
                    @TrackedDevicePosition.performed += instance.OnTrackedDevicePosition;
                    @TrackedDevicePosition.canceled += instance.OnTrackedDevicePosition;
                    @TrackedDeviceOrientation.started += instance.OnTrackedDeviceOrientation;
                    @TrackedDeviceOrientation.performed += instance.OnTrackedDeviceOrientation;
                    @TrackedDeviceOrientation.canceled += instance.OnTrackedDeviceOrientation;
                    @ToggleInventory.started += instance.OnToggleInventory;
                    @ToggleInventory.performed += instance.OnToggleInventory;
                    @ToggleInventory.canceled += instance.OnToggleInventory;
                    @ToggleDamageScreen.started += instance.OnToggleDamageScreen;
                    @ToggleDamageScreen.performed += instance.OnToggleDamageScreen;
                    @ToggleDamageScreen.canceled += instance.OnToggleDamageScreen;
                }
            }
        }
        public UIActions @UI => new UIActions(this);
        public interface IControllableActions
        {
            void OnJump(InputAction.CallbackContext context);
            void OnRun(InputAction.CallbackContext context);
            void OnMove(InputAction.CallbackContext context);
            void OnMouseX(InputAction.CallbackContext context);
            void OnMouseY(InputAction.CallbackContext context);
        }
        public interface IHumanoidActions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnRunStart(InputAction.CallbackContext context);
            void OnRunFinish(InputAction.CallbackContext context);
            void OnJump(InputAction.CallbackContext context);
            void OnMouseX(InputAction.CallbackContext context);
            void OnMouseY(InputAction.CallbackContext context);
            void OnItemInteract(InputAction.CallbackContext context);
            void OnItemThrow(InputAction.CallbackContext context);
            void OnToggleInventory(InputAction.CallbackContext context);
            void OnAim(InputAction.CallbackContext context);
            void OnShoot(InputAction.CallbackContext context);
            void OnReload(InputAction.CallbackContext context);
            void OnChangeFireMode(InputAction.CallbackContext context);
            void OnToggleDamageSettings(InputAction.CallbackContext context);
        }
        public interface IUIActions
        {
            void OnNavigate(InputAction.CallbackContext context);
            void OnSubmit(InputAction.CallbackContext context);
            void OnCancel(InputAction.CallbackContext context);
            void OnPoint(InputAction.CallbackContext context);
            void OnClick(InputAction.CallbackContext context);
            void OnScrollWheel(InputAction.CallbackContext context);
            void OnMiddleClick(InputAction.CallbackContext context);
            void OnRightClick(InputAction.CallbackContext context);
            void OnTrackedDevicePosition(InputAction.CallbackContext context);
            void OnTrackedDeviceOrientation(InputAction.CallbackContext context);
            void OnToggleInventory(InputAction.CallbackContext context);
            void OnToggleDamageScreen(InputAction.CallbackContext context);
        }
    }
}
